# Generated by Django 5.2.1 on 2025-05-12 07:06

import django.core.validators
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['department', 'designation', 'faculty_id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-enrollment_year', 'student_id']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faculty',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='office_room',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='publications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(default='M.Tech', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BTech', 'B.Tech'), ('MTech', 'M.Tech'), ('MSc', 'M.Sc'), ('PhD', 'Ph.D')], default='BTech', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=users.models.current_year),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('HOD', 'Head of Department'), ('Dean', 'Dean')], default='Assistant Professor', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default=users.models.default_batch, max_length=10),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['department'], name='users_facul_departm_f3d096_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['designation'], name='users_facul_designa_b70f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['faculty_id'], name='users_facul_faculty_09a786_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_year'], name='users_stude_enrollm_7b110c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_semester'], name='users_stude_current_b136a8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='users_stude_student_908f14_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch'], name='users_stude_branch_60bcbd_idx'),
        ),
    ]
